version: '3.9'
services:
  movies-explorer-frontend:
    build:
      context: .
      target: dev-envs
    container_name: movies-explorer-frontend
    ports:
      - "3021:3021"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    name: nginx-proxy
